version: "3.9"

services:

  hyrcania-app:
    build: .
    container_name: hyrcania-app

    ports:
      - "8080:5000"

    environment:
      APP_NAME: Hyrcania
      APP_ENV: production
      DATABASE_HOST: hyrcania-db
      DATABASE_PORT: 5432
      DATABASE_NAME: hyrcania
      DATABASE_USER: admin
      DATABASE_PASSWORD: password

    depends_on:
      - hyrcania-db

    restart: unless-stopped

    networks:
      - hyrcania-network


  hyrcania-db:
    image: postgres:16

    container_name: hyrcania-db

    environment:
      POSTGRES_DB: hyrcania
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: unless-stopped

    networks:
      - hyrcania-network


volumes:

  postgres-data:


networks:

  hyrcania-network:
    driver: bridge